#--------------------------------------------#
# SnakeBat v1.0 Configuration file
# Mike Martinez M.S. Megan Graham
#--------------------------------------------#

#----- Folder csv file
folders: "folders.csv" # Keep the same

#----- RMS Power calculation parameters
segmentDuration: "1"
fileType: ".WAV"
samplingRate: "250000"
bwFilterFrom: "30000"
bwFilterTo: "70000"



